"""Added account table

Revision ID: 1ab5419e503
Revises: None
Create Date: 2013-11-10 22:59:50.754556

"""

# revision identifiers, used by Alembic.
revision = '1ab5419e503'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
