"""some message2

Revision ID: 1d3870e5033
Revises: 58ccd00df33
Create Date: 2013-11-12 14:33:49.143484

"""

# revision identifiers, used by Alembic.
revision = '1d3870e5033'
down_revision = '58ccd00df33'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('name2', sa.Text(), nullable=True))
    op.drop_column('models', 'name1')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('name1', mysql.TEXT(), nullable=True))
    op.drop_column('models', 'name2')
    ### end Alembic commands ###
