"""some message

Revision ID: 58ccd00df33
Revises: 2faf296f8a5
Create Date: 2013-11-12 14:28:30.767026

"""

# revision identifiers, used by Alembic.
revision = '58ccd00df33'
down_revision = '2faf296f8a5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('name1', sa.Text(), nullable=True))
    op.drop_column('models', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('name', mysql.TEXT(), nullable=True))
    op.drop_column('models', 'name1')
    ### end Alembic commands ###
